import { Customer } from "./definitions";

export const customers: Customer[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@example.com",
    company: "Acme Corp",
    status: "active",
    totalOrders: 12,
    totalSpent: 12500,
    lastOrderDate: "2024-03-15",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.j@techfirm.com",
    company: "TechFirm Inc",
    status: "active",
    totalOrders: 8,
    totalSpent: 8750,
    lastOrderDate: "2024-03-10",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "3",
    name: "Michael Brown",
    email: "m.brown@globaltech.com",
    company: "GlobalTech Solutions",
    status: "inactive",
    totalOrders: 5,
    totalSpent: 4500,
    lastOrderDate: "2024-02-28",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.d@innovate.com",
    company: "Innovate Labs",
    status: "active",
    totalOrders: 15,
    totalSpent: 18750,
    lastOrderDate: "2024-03-18",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "5",
    name: "Robert Wilson",
    email: "r.wilson@megacorp.com",
    company: "MegaCorp Industries",
    status: "active",
    totalOrders: 20,
    totalSpent: 25000,
    lastOrderDate: "2024-03-20",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "6",
    name: "Lisa Anderson",
    email: "l.anderson@startup.com",
    company: "Startup Ventures",
    status: "inactive",
    totalOrders: 3,
    totalSpent: 3000,
    lastOrderDate: "2024-02-15",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "7",
    name: "David Miller",
    email: "d.miller@enterprise.com",
    company: "Enterprise Solutions",
    status: "active",
    totalOrders: 18,
    totalSpent: 22500,
    lastOrderDate: "2024-03-17",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "8",
    name: "Jennifer Taylor",
    email: "j.taylor@digital.com",
    company: "Digital Dynamics",
    status: "active",
    totalOrders: 10,
    totalSpent: 15000,
    lastOrderDate: "2024-03-12",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "9",
    name: "James White",
    email: "j.white@future.com",
    company: "Future Tech",
    status: "inactive",
    totalOrders: 6,
    totalSpent: 7500,
    lastOrderDate: "2024-02-20",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "10",
    name: "Patricia Martinez",
    email: "p.martinez@creative.com",
    company: "Creative Solutions",
    status: "active",
    totalOrders: 14,
    totalSpent: 17500,
    lastOrderDate: "2024-03-16",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "11",
    name: "Thomas Garcia",
    email: "t.garcia@nextgen.com",
    company: "NextGen Technologies",
    status: "active",
    totalOrders: 9,
    totalSpent: 11250,
    lastOrderDate: "2024-03-14",
    image_url: "/customers/default-avatar.svg",
  },
  {
    id: "12",
    name: "Elizabeth Robinson",
    email: "e.robinson@smart.com",
    company: "Smart Systems",
    status: "inactive",
    totalOrders: 4,
    totalSpent: 5000,
    lastOrderDate: "2024-02-25",
    image_url: "/customers/default-avatar.svg",
  },
];
