ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS company VARCHAR(255),
  ADD COLUMN IF NOT EXISTS status VARCHAR(32),
  ADD COLUMN IF NOT EXISTS total_orders INT,
  ADD COLUMN IF NOT EXISTS total_spent INT,
  ADD COLUMN IF NOT EXISTS last_order_date DATE; 